client:
  keystorePathValidCerts: "./testDataTemplates/certificates/ecc/fachmodulClient/valid"
  keystorePathAlternativeCerts: "./testDataTemplates/certificates/ecc/fachmodulClient/valid-alternative"
  keystorePathInvalidCerts: "./testDataTemplates/certificates/ecc/fachmodulClient/invalid"

testObject:
  name: "Server 0815"
  type: "TlsServer"
  ipAddressOrFqdn: "HOSTNAME_TO_REPLACE"
  port: 8443
  ocspGracePeriodSeconds: 0
  tslDownloadIntervalSeconds: 2
  tslProcessingTimeSeconds: 2

ocspResponder:
  ipAddressOrFqdn: "HOSTNAME_TO_REPLACE"
  port: 8083
  appPath: "externalStartup"

tslProvider:
  ipAddressOrFqdn: "HOSTNAME_TO_REPLACE"
  port: 8084
  appPath: "externalStartup"
