testObject:
  name: "Server 0815"
  testObjectType: "IntermediaerServer"
  ipAddressOrFqdn: "HOSTNAME_TO_REPLACE"
  port: 8443
  ocspGracePeriodSeconds: 0
  tslDownloadIntervalSeconds: 2
  tslProcessingTimeSeconds: 2

ocspResponder:
  ipAddressOrFqdn: "HOSTNAME_TO_REPLACE"
  port: 8083


tslProvider:
  ipAddressOrFqdn: "HOSTNAME_TO_REPLACE"
  port: 8084
