testObject:
  name: "Server 0815"
  testObjectType: "IdpFachdienst"
  ocspGracePeriodSeconds: 0
  tslDownloadIntervalSeconds: 5
  tslProcessingTimeSeconds: 3
  scriptUseCase:
    scriptPath: "./docs/sample_script.cmd"

ocspResponder:
  ipAddressOrFqdn: "127.0.0.1"
  port: 8083

tslProvider:
  ipAddressOrFqdn: "127.0.0.1"
  port: 8084
