testObject:
  name: "Server 0815"
  testObjectType: "IntermediaerServer"
  ipAddressOrFqdn: "HOSTNAME_TO_REPLACE"
  port: 8443
  ocspGracePeriodSeconds: 0
  ocspToleranceProducedAtPastSeconds: 10
  ocspToleranceProducedAtFutureSeconds: 20
  tslDownloadIntervalSeconds: 2
  tslProcessingTimeSeconds: 2

ocspResponder:
  ipAddressOrFqdn: "HOSTNAME_TO_REPLACE"
  port: 8083
  appPath: "externalStartup"

tslProvider:
  ipAddressOrFqdn: "HOSTNAME_TO_REPLACE"
  port: 8084
  appPath: "externalStartup"
