server:
  port: 8443
  ssl:
    key-store: classpath:certificates/steak-ecc/ee_default.p12
    key-store-password: "00"
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.2, TLSv1.3
    client-auth: need
    ciphers: ECDHE-ECDSA-AES256-GCM-SHA384, ECDHE-ECDSA-AES128-GCM-SHA256, DHE-RSA-AES256-SHA, DHE-RSA-AES128-SHA

  error:
    include-message: always
  tomcat:
    accesslog:
      enabled: true

handshake-interception:
  enabled: true

ocsp:
  enabled: true
  service-url: http://localhost:8083/ocsp
  grace-period-seconds: 0
  ocsp-timeout-seconds: 10
  tolerate-ocsp-failure: false

tsl-procurer:
  # use constant TSL_SEQNR_PARAM_ENDPOINT for activeTslSeqNr in source code
  initialTslPrimaryDownloadUrl: "http://localhost:8084/tsl/tsl.xml?activeTslSeqNr=0"
  downloadInterval: 2
  repetitions: 4
  tslGracePeriodDays: 0
